import twilio from 'twilio';
import { EventEmitter } from 'events';
import { logOut, logError } from '../utils/logger.js';
import VoiceResponse from 'twilio/lib/twiml/VoiceResponse.js';
import { CachedAssetsService } from './CachedAssetsService.js';
import { ConversationRelayConfig } from '../interfaces/ConversationRelay.js';

/**
 * Interface for status callback object
 */
interface StatusCallback {
    CallSid: string;
    [key: string]: any;
}

/**
 * Service class for handling Twilio-related operations including making calls, sending SMS and generating TwiML for the Conversation Relay service.
 * 
 * @class
 * @property {string} accountSid - Twilio account SID from environment variables
 * @property {string} authToken - Twilio authentication token from environment variables
 * @property {string} fromNumber - Twilio phone number to use as the sender
 * @property {twilio.Twilio} twilioClient - Initialized Twilio client instance
 */
class TwilioService extends EventEmitter {
    private accountSid: string;
    private authToken: string;
    private fromNumber: string;
    private twilioClient: twilio.Twilio;

    constructor() {
        super();
        this.accountSid = process.env.ACCOUNT_SID || '';
        this.authToken = process.env.AUTH_TOKEN || '';
        this.fromNumber = process.env.FROM_NUMBER || '';
        this.twilioClient = twilio(process.env.ACCOUNT_SID || '', process.env.AUTH_TOKEN || '');
        // this.twilioClient = twilio(process.env.API_KEY, process.env.API_SECRET, { process.env.ACCOUNT_SID });    // Some issue here with the API key and secret
    }

    /**
     * Initialize the service
     */
    async initialize(): Promise<void> {
        logOut('TwilioService', 'TwilioService initialized');
    }

    /**
     * Helper function to filter out unset values from configuration
     */
    private filterUnsetValues(config: any): any {
        const filtered: any = {};

        Object.entries(config).forEach(([key, value]) => {
            if (value !== null && value !== undefined && value !== '' &&
                !(Array.isArray(value) && value.length === 0)) {
                filtered[key] = value;
            }
        });

        return filtered;
    }

    /**
     * Makes an outbound call and connects it to the Conversation Relay service.
     * The call is automatically recorded and uses TwiML generated by connectConversationRelay.
     *
     * @param {string} serverBaseUrl - Base URL for the Conversation Relay WebSocket server (without wss:// prefix)
     * @param {string} toNumber - The destination phone number in E.164 format
     * @param {CachedAssetsService} cachedAssetsService - Service for accessing configuration
     * @param {string} callReference - Unique reference ID for the customer
     * @returns {Promise<any>} The Twilio call object if successful
     * @throws {Error} If the call cannot be initiated or other Twilio API errors occur
     */
    async makeOutboundCall(serverBaseUrl: string, toNumber: string, cachedAssetsService: CachedAssetsService, callReference: string = ""): Promise<any> {
        try {
            const conversationRelay = await this.connectConversationRelay(serverBaseUrl, cachedAssetsService, callReference);

            if (!conversationRelay) {
                throw new Error('Failed to generate TwiML for conversation relay');
            }

            const call = await this.twilioClient.calls.create({
                to: toNumber,
                from: this.fromNumber,
                twiml: conversationRelay.toString(),
                record: true,
            });

            logOut('TwilioService', `Made a call from: ${this.fromNumber} to: ${toNumber}`);
            return call;

        } catch (error) {
            logError('TwilioService', `Make Outbound call error: ${error instanceof Error ? error.message : String(error)}`);
            throw error;
        }
    }

    /**
     * Sends an SMS message using the configured Twilio number.
     * 
     * @param {string} to - The destination phone number in E.164 format
     * @param {string} message - The message content to send
     * @returns {Promise<string|null>} The Twilio message SID if successful, null if sending fails
     */
    async sendSMS(to: string, message: string): Promise<string | null> {
        try {
            logOut('TwilioService', `Sending SMS to: ${to} with message: ${message}`);

            const response = await this.twilioClient.messages.create({
                body: message,
                from: this.fromNumber,
                to: to
            });
            return response.sid;
        } catch (error) {
            logError('TwilioService', `Error sending SMS: ${error instanceof Error ? error.message : String(error)}`);
            return null;
        }
    }

    /**
     * Generates TwiML to connect a call to the Conversation Relay service.
     * Uses dynamic configuration from CachedAssetsService instead of hardcoded values.
     * Can be used for both inbound and outbound calls.
     *
     * @param {string} serverBaseUrl - Base URL for the Conversation Relay WebSocket server (without wss:// prefix)
     * @param {CachedAssetsService} cachedAssetsService - Service for accessing configuration
     * @param {string} callReference - Unique reference ID for the customer
     * @returns {Promise<twilio.twiml.VoiceResponse|null>} The TwiML response object if successful, null if generation fails
     */
    async connectConversationRelay(serverBaseUrl: string, cachedAssetsService: CachedAssetsService, callReference: string = ""): Promise<twilio.twiml.VoiceResponse | null> {
        try {
            logOut('TwilioService', `Generating TwiML for call with callReference: ${callReference}`);

            // Get configuration from CachedAssetsService
            const usedConfig = cachedAssetsService.getUsedConfig();
            const config = cachedAssetsService.getConversationRelayConfig(usedConfig.configuration);
            const languages = cachedAssetsService.getLanguages();

            if (!config) {
                logError('TwilioService', 'No ConversationRelay configuration found');
                return null;
            }

            // Generate the TwiML with dynamic configuration
            const response: VoiceResponse = new twilio.twiml.VoiceResponse();
            const connect: VoiceResponse.Connect = response.connect();
            const filteredConfig = this.filterUnsetValues(config);
            const conversationRelay: VoiceResponse.ConversationRelay = connect.conversationRelay({
                url: `wss://${serverBaseUrl}/conversation-relay`,
                ...filteredConfig
            } as any);

            // Add language configurations if available
            if (languages) {
                Object.keys(languages).forEach(langCode => {
                    const langConfig = languages[langCode];
                    if (langConfig && langConfig.ttsProvider && langConfig.voice) {
                        conversationRelay.language({
                            code: langCode,
                            ttsProvider: langConfig.ttsProvider,
                            voice: langConfig.voice,
                        });
                    }
                });
            }

            conversationRelay.parameter({
                name: 'callReference',
                value: callReference
            });

            // logOut('TwilioService', `Generated TwiML using Helper for call: ${response.toString()}`);

            return response;

        } catch (error) {
            logError('TwilioService', `Error generating call TwiML: ${error instanceof Error ? error.message : String(error)}`);
            return null;
        }
    }


    /**
     * Evaluate the status callback received. This will be used in the LLM to determine the next steps.
     * If there is nothing to be done, just null the response.
     * 
     * @param statusCallback - The status callback object from Twilio
     * @returns The evaluated status callback object or null
     */
    async evaluateStatusCallback(statusCallback: StatusCallback): Promise<StatusCallback | null> {
        try {
            logOut('TwilioService', `Evaluating status callback: ${JSON.stringify(statusCallback)}`);
            // Do something and then emit the event type
            const callSid = statusCallback.CallSid;
            logOut('TwilioService', `Returning evaluated status callback for callSid: ${callSid}`);
            return statusCallback;
        } catch (error) {
            logError('TwilioService', `Error evaluating status callback: ${error instanceof Error ? error.message : String(error)}`);
            return null;
        }
    }
}

export { TwilioService };
